### ISSUE TITLE
Initial value ignored

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [spion/array-2d.js#1]
The default value take in the constructor is ignored in your code you always use 0 as a value.

Best

**Comment by GuillaumeLeclerc** [comment]
Thank you !

**Comment by mbutler** [comment]
Looks like the npm package hasn't been updated with this fix. I've updated my local copy, but just FYI. Thanks!

**Comment by spion** [comment]
Sorry about that. I updated the package as well, v1.0.2 should be good.
